name = "Speasy"
uuid = "09b745ad-c67d-442f-94a6-c7f4d1e4d861"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"
TimeseriesTools = "380cddd1-6ef2-46ca-b087-e7151fb095ff"

[extensions]
DimensionalDataExt = "DimensionalData"
MakieExt = "Makie"
TimeSeriesExt = "TimeSeries"
TimeseriesToolsExt = "TimeseriesTools"

[compat]
CondaPkg = "0.2.24"
Dates = "1"
DimensionalData = "0.29"
Makie = "0.21, 0.22"
PythonCall = "0.9.23"
TimeSeries = "0.24.2"
TimeseriesTools = "0.6"
Unitful = "1.22"
julia = "1.10"
