name = "Speasy"
uuid = "09b745ad-c67d-442f-94a6-c7f4d1e4d861"
version = "0.4.9"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]

[workspace]
projects = ["docs", "test"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
SpaceDataModel = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnixTimes = "ab1a18e7-b408-4913-896c-624bb82ed7f4"

[weakdeps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"
TimeseriesTools = "380cddd1-6ef2-46ca-b087-e7151fb095ff"

[extensions]
SpeasyDimensionalDataExt = "DimensionalData"

[compat]
Accessors = "0.1"
ConcreteStructs = "0.2.3"
DimensionalData = "0.29"
Makie = "0.21, 0.22, 0.23, 0.24"
PythonCall = "0.9.23"
SpaceDataModel = "0.2.3"
TimeSeries = "0.24.2"
TimeseriesTools = "0.6, 0.7"
Unitful = "1.22"
UnixTimes = "1.7"
julia = "1.10"
